name : CI/CD SpringBoot to AWS EC2 #name of target action
run-name : $${{github.actor}} is setting Github Actions âœ¨âœ¨âœ¨
on :
  push: # condition of starting action
    branches : # target branches
      - main

env:
  PROJECT_NAME : crud #name of project
  BUCKET_NAME : crud341410 # name of s3 bucket
  CODE_DEPLOY_APP_NAME: cicdapp
  DEPLOYMENT_GROUP_NAME : cicdapp_deploy
jobs:
  build: # build backend and test
    runs-on : ubuntu-latest # environment of OS

    steps: #startoing steps in instance
      - name : Checkout source code. #get code from repo
        uses : actions/checkout@v2

      - name: Set up Java JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
        
      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name : Configure AWS credentials
        uses: aws-actions/configure-aws-credential@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$BUCKET_NAME, bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
        


      - name: Set environment variables for database
        env : # env
          DB_URL : ${{secrets.DB_URL}}
          DB_USERNAME : ${{secrets.DB_USERNAME}}
          DB_PASSWORD : ${{secrets.DB_PASSWORD}}
        run : |
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

########################################################################
#  frontend: #build frontend and test
#    runs-on : ubuntu-latest
#    needs : backend # start building after completin of backend
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '16'  # version of Node.js that is used in React
#
#      - name: Install frontend dependencies
#        working-directory: ./frontend  # change path to frontend directory
#        run: npm install
#
#      - name: Build frontend
#        working-directory: ./frontend
#        run: npm run build
#
#      - name: Run frontend tests
#        working-directory: ./frontend
#        run: npm test


  deploy:
    runs-on : ubuntu-latest
    needs : backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deply to server
        run : |
          echo "Deploying to server...ðŸª„"
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
              
          # backend deploy
          cd C:\Users\eldh1\Downloads\CRUD-API-main\CRUD-API-main
          git pull origin main
          ./gradlew build -Dspring.datasource.url=${{ secrets.DB_URL }} \
                          -Dspring.datasource.username=${{ secrets.DB_USERNAME }} \
                          -Dspring.datasource.password=${{ secrets.DB_PASSWORD }}
          pm2 restart backend-api
          
          # backend deploy
          cd C:\Users\eldh1\Downloads\frontend
          git pull origin main
          npm install
          npm run build
          cp -R build/* /path/to/your/nginx/html
        EOF
